### ISSUE TITLE
Cannot find path when using tsm in GitHub actions

### ISSUE THREAD

**Issue by Jason-Abbott** [lukeed/uvu#157]
I am so far stumped by a path error trying to run uvu in a GitHub action with `tsm`.

It runs fine locally (Win11) but on GitHub or with https://github.com/nektos/act (local action runner) I see this difference:

*Proving same Node version*
```sh
PS E:\dev\toba\family-law> node -v
v14.18.1

root@docker-desktop:/mnt/e/dev/toba/family-law# node -v
v14.18.1
```

*Running `tsm` directly on a singe test file works correctly in both environments. Both ...*
```sh
PS E:\dev\toba\family-law> node_modules/.bin/tsm core/utils.test.ts 
root@docker-desktop:/mnt/e/dev/toba/family-law# node_modules/.bin/tsm core/utils.test.ts
```
*... produce ...*
```sh
  Total:     14
  Passed:    14
  Skipped:   0
  Duration:  2.19ms
```
*However, running the tests with uvu, while working fine on Win11* (full `tsm` path not necessary but used to rule out issue),
```sh
PS E:\dev\toba\family-law> node_modules/.bin/uvu -r node_modules/tsm/require.js core .test.ts
Preparing data pool. SQL echo is enabled.
db\generators\erd.test.ts
• •   (2 / 2)
[...]
```
*does this in GitHub actions:*
```sh
root@docker-desktop:/mnt/e/dev/toba/family-law# node_modules/.bin/uvu -r node_modules/tsm/require.js core .test.ts
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:489:10)
    at Object.readFileSync (fs.js:393:35)
    at Object.<anonymous> (/mnt/e/dev/toba/family-law/core/db/client.ts:48:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.config.<computed>.r._compile (/mnt/e/dev/toba/family-law/node_modules/tsm/require.js:1:1032)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.loader (/mnt/e/dev/toba/family-law/node_modules/tsm/require.js:1:1052)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

I will keep digging into this but would be grateful for any quick observations.

**Comment by Jason-Abbott** [comment]
This was totally on me. A file path defined by an environment variable was mistakenly referenced on module load rather than waiting for a function call (which doesn't happen in testing). That environment variable isn't defined in the test environment.
