### ISSUE TITLE
theres a bug with node17 + uvu + experimental loader

### ISSUE THREAD

**Issue by noahehall** [lukeed/uvu#163]
context:
- using node17 experimental loader to automatically remove type annotations from javascript files
-  fyi: works with node16
- when running the experimental loader through uvu on node17: fails

theres a lot of stuff here, but of importance is this line
```sh
(node:611146) WARNING: Exited the environment with code 1
    at exit (node:internal/process/per_thread:189:13)
    at /home/poop/git/foss/nodeproto/node_modules/.pnpm/uvu@0.5.2/node_modules/uvu/bin.js:32:12
```

log
```sh
poop@spaceship:~/git/foss/nodeproto/packages/libraries/buildproto
07:38 AM (shiz-broken $=) 
$ pnpm repo:test

> @nodeproto/buildproto@0.0.0 repo:test /home/poop/git/foss/nodeproto/packages/libraries/buildproto
> NODE_OPTIONS="$npm_package_config_NODE_OPTIONS" uvu ./src "test.(m|c)?js"

(node:611146) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at initializeLoader (node:internal/process/esm_loader:59:3)
    at loadESM (node:internal/process/esm_loader:87:11)
    at runMainESM (node:internal/modules/run_main:48:21)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:78:5)
    at node:internal/main/run_main_module:17:47


 custom logic {
  url: 'file:///home/poop/git/foss/nodeproto/packages/libraries/buildproto/src/esbuild/create.esbuild.config.test.mjs',
  isCjs: false,
  isFlow: false
}
TypeError [ERR_INVALID_FILE_URL_HOST]: File URL host must be "localhost" or empty on linux
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at getPathFromURLPosix (node:internal/url:1449:11)
    at fileURLToPath (node:internal/url:1472:50)
    at toPathIfFileURL (node:internal/url:1551:10)
    at __node_internal_ (node:internal/fs/utils:681:16)
    at statSync (node:fs:1529:10)
    at fileExists (node:internal/modules/esm/resolve:260:10)
    at resolveExtensions (node:internal/modules/esm/resolve:335:9)
    at resolveExtensionsWithTryExactName (node:internal/modules/esm/resolve:322:10)
    at finalizeResolution (node:internal/modules/esm/resolve:375:16)
    at moduleResolve (node:internal/modules/esm/resolve:915:10)
    at defaultResolve (node:internal/modules/esm/resolve:1005:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:475:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:245:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36)
(node:611146) WARNING: Exited the environment with code 1
    at exit (node:internal/process/per_thread:189:13)
    at /home/poop/git/foss/nodeproto/node_modules/.pnpm/uvu@0.5.2/node_modules/uvu/bin.js:32:12
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by noahehall** [comment]
will include more details later, but i need to go to work

**Comment by lukeed** [comment]
I have zero idea what's going on here. Going to need more information – but likely a reproduction – to stand a chance at helping you out.

My gut impression is that this is an issue with your experimental loader (whatever it is, dunno) and it's only surfacing as an error / caught by uvu.

**Comment by noahehall** [comment]
you are exactly right my friend - just figured it out

**Comment by noahehall** [comment]
just FYI

https://github.com/nodejs/node/issues/41320
