### ISSUE TITLE
Assertion failure output trims newlines in string match failure

### ISSUE THREAD

**Issue by aral** [lukeed/uvu#199]
Output of assertion failure:

```
FAIL  CLI  "version"
Version command output is as expected.  (equal)

    Actual:
    --nodekit,·1.0.0
    Expected:
    ++nodekit,·1.0.0
    
at assert (file:///home/aral/Projects/small-web/nodekit/app/node_modules/uvu/assert/index.mjs:33:8)
at Module.equal (file:///home/aral/Projects/small-web/nodekit/app/node_modules/uvu/assert/index.mjs:45:2)
```

(The first line has a newline at the end but it is being trimmed, making it impossible to tell what the difference is from looking at the error message.)

**Comment by rschristian** [comment]
Looks like a duplicate of #110
