### ISSUE TITLE
Multiples requires 

### ISSUE THREAD

**Issue by tavoli** [lukeed/uvu#204]
I want to use the path alias from tsconfig.json and I install the [tsconfig-paths/register](https://www.npmjs.com/package/tsconfig-paths) module.

I play this with the command: `uvu -r tsm -r tsconfig-paths/register src \.spec\.ts$`

And I take:

```
/home/lima/1menu/order-front/src/components/Nav.svelte:1
<script>
^

SyntaxError: Unexpected token '<'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.loader (/home/lima/1menu/order-front/node_modules/tsm/require.js:1:1052)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.apply (/home/lima/1menu/order-front/src/components/Nav.spec.ts:1:292)
```

Happens that the filter doesn't work with multiple requirements and tried run components instead test files.

**Comment by tavoli** [comment]
It's my mistake.
