### ISSUE TITLE
Assertion error when comparing non-string vs string values in uvu/assert

### ISSUE THREAD

**Issue by krismuniz** [lukeed/uvu#26]
Hello :wave:!

I think I found an issue in `uvu/assert`. Let me know how I can help!

### Summary

When using the `assert.equal` method for testing that an arbitrary value equals a string, an unexpected error happens:

```
Cannot read property 'split' of <value>
```

### Reproduction

Module version: `uvu@0.2.2`:

```js
import { test } from 'uvu';
import * as assert from 'uvu/assert';

test('failing test', function () {
  const myValue = null;
  assert.equal(myValue, 'mahstring');
});

test.run();
```

Produces this error:

```
Cannot read property 'split' of null

  at Diff.tokenize ([CWD]/node_modules/diff/lib/diff/base.js:234:18)
  at Diff.diff ([CWD]/node_modules/diff/lib/diff/base.js:45:39)
  at Object.diffChars ([CWD]/node_modules/diff/lib/diff/character.js:35:24)

  at chars ([CWD]/node_modules/uvu/diff/index.js:79:17)
  at compare ([CWD]/node_modules/uvu/diff/index.js:202:10)
  at assert ([CWD]/node_modules/uvu/assert/index.js:30:28)
  at Object.equal ([CWD]/node_modules/uvu/assert/index.js:43:2)

  at Object.handler ([CWD]/test/index.js:22:10)

  at Number.runner ([CWD]/node_modules/uvu/dist/index.js:70:16)
  at exec ([CWD]/node_modules/uvu/dist/index.js:124:39)
```

### Potential Solution

It seems to be happening when the `diff` library attempts to tokenize a non-string value.

I believe that the `uvu` code that triggers this `diff.diffChars()` (and therefore the tokenizer) on a non-string is:

https://github.com/lukeed/uvu/blob/94e541cb8447b83b6a9e98d04262d6fc7498278d/src/diff.js#L201-L203

This modification – additional condition is added – seems to fix the issue. 

```diff
-  if (typeof expect == 'string') {
+  if (typeof expect == 'string' && typeof input == 'string') {
 	return chars(input, expect);
}
```

But I am not sure of the implications of this change.

---

I hope this helps. Thanks for this awesome project 👋

**Comment by lukeed** [comment]
Thank you for the report :)
