### ISSUE TITLE
Date comparison isn't very useful

### ISSUE THREAD

**Issue by antony** [lukeed/uvu#92]
Comparing dates with shallow `.equals` will match any two dates, and matching dates with `is` results in some very obtuse output which makes it impossible to debug.

# input

```js
const { test } = require('uvu')
const assert = require('uvu/assert')

test('dates', () => {
    const a = new Date()
    const b = new Date(new Date().setMonth(5))
    assert.is(a, b)
})

test.run()
```
# output

```sh
npx uvu
index.spec.js
✘   (0 / 1)

   FAIL  "dates"
    Expected values to be strictly equal:  (is)

        ++"2021-06-04T11:40:40.529Z"    (Expected)
        --                        {}    (Actual)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
    at assert (/home/ant/Projects/uvutest/node_modules/uvu/assert/index.js:31:8)
    at Object.is (/home/ant/Projects/uvutest/node_modules/uvu/assert/index.js:39:2)
    at Object.handler (/home/ant/Projects/uvutest/index.spec.js:7:12)
    at Number.runner (/home/ant/Projects/uvutest/node_modules/uvu/dist/index.js:77:16)
    at exec (file:///home/ant/Projects/uvutest/node_modules/uvu/dist/index.mjs:131:39)
    at Module.run (file:///home/ant/Projects/uvutest/node_modules/uvu/run/index.mjs:13:8)
    at async /home/ant/Projects/uvutest/node_modules/uvu/bin.js:26:5



  Total:     1
  Passed:    0
  Skipped:   0
  Duration:  2.36ms
```

**Comment by talentlessguy** [comment]
with built-in `assert.equal` it converts both date objects to an ISO string and compares them

```
AssertionError [ERR_ASSERTION]: 2021-05-31T18:09:34.334Z == 2021-07-01T18:09:34.334Z
```

possible solution is to check if an object is an instance of `Date` and then apply `toISOString()`

**Comment by alextes** [comment]
How do we feel about the suggested solution, would a PR be welcome? 😄
